### ISSUE TITLE
Package module list, consider grouping by cma

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/odig#1]
Currently the module list on a package page is simply the list of all toplevel interfaces exported by the package in alphabetical order. We could could however first group them by cma and then by alphabetical order. 

This could match the idea of mapping cmas to `odig` subpackages.

**Comment by trefis** [comment]
As discussed [here](https://github.com/ocaml-doc/odoc/issues/12), the current `odoc listing` subcommand is not very useful (for odig and in general).
I plan to move to something similar to what ocamldoc does, i.e. accepting an arbitrary file in the ocamldoc syntax and generating the corresponding html file.
This is currently what odig uses for its ocamldoc backend by reusing the `{!modules: ...}` command (see [here](https://github.com/dbuenzli/odig/blob/master/src/odig_ocamldoc.ml#L135)).

IIUC this would work well with the approach you propose here, just use `{!modules: ...}` as many times as there are `cma` files.

I do however think that while this seems like a good approach in general, there should be a way for packagers to override that behavior. Perhaps by installing a "library.odig" file (or something similar) which odig would use for the package page instead of the default one (probably wrapping it with the good navigations links in the header, footer, etc.).
This seems like a good way for packagers to have control over the interface they expose to user.

For example, janestreet packages could use that to show the content of their `Std` module, instead of the units listing which will list things like `Core__Whatever` which they'd rather not show.

**Comment by dbuenzli** [comment]
This is now implemented for the `odoc` backend as part of cee4611c737697897fe8f7. @trefis Your wish is being tracked in #18.

**Comment by dbuenzli** [comment]
Since 9e555ddab17c57f808555 and thanks to @trefis' odoc `--index-of` this is now unified and available in both backends.
