### ISSUE TITLE
Use .cmt when .cmti is not present

### ISSUE THREAD

**Issue by trefis** [dbuenzli/odig#2]
It is a common pattern in ocaml packages (cf. cohttp, core, etc.) to have modules defined only by a `.ml` file (i.e. without a `.mli`) as they export only module types.
In this case you won't have a `.cmti` file but only a `.cmt` (which will contain all the doc comments one wants).
You should use these `.cmt` files.

**Comment by dbuenzli** [comment]
> to have modules defined only by a .ml file (i.e. without a .mli) as they export only module types.

Shouldn't these be in an `mli` file only ? This would allow to generate `cmti`s and allow me to keep the idea that only what you install as `cmti` will define what is documented.

**Comment by dbuenzli** [comment]
For now the idea is that packages define the API they want to be documented by installing `mli` and `cmi` files (`ocamldoc` backend) and `cmti` files (`odoc` backend). See `odig help packaging`.

**Comment by lpw25** [comment]
The current scheme provides no way to document modules that are defined by only an ml file. There are plenty of such modules, so I really think this needs to change. If there is a `.cmt` file but no `.cmti` file for a module then `odig` should pass the `cmt` file to `odoc`.

I can see no reason that someone would want to install the `.cmt` file but not the `.cmti` file of a module which does have a `mli` file, so I think the existence of a `.cmt` without a `.cmti` can safely be taken as indicating that only an `ml` file was used. When this isn't the case `odoc` can detect it and give a warning (the presence of an `mli` file is noted in the `cmt` file).

Personally, I would also like to see modules that only have a `.cmi` file be included in the documentation by default. They are part of the user-visible interface so should be part of the documentation. This would allow `odig` to produce passable documentation for old projects that have not updated their build to install `.cmti`/`.cmt` files. For the rare cases where a `.cmi` must be installed but should not be included in documentation the user could include a `@hidden` tag in the main doc comment -- which `odoc` would take as an indication that the module should not appear (although it's information could still be used for checking references and expanding module types). This supported for `@hidden` isn't implemented yet but will be needed for other reasons anyway.

**Comment by dbuenzli** [comment]
> I can see no reason that someone would want to install the .cmt file but not the .cmti file of a module which does have a mli file,

I think the debugging stuff (libmonda) needs the `cmt` files and you may not want to install a `.cmti` file because you want to hide these names from the end-user (e.g. because you make them available through another namespacing module). Besides it is an established good practice to write mli files to define your APIs.

**Comment by lpw25** [comment]
> I think the debugging stuff (libmonda) needs the cmt files and you may not want to install a .cmti file because you want to hide these names from the end-user (e.g. because you make them available through another namespacing module).

Good point. Although to me that just shows another problem with the current scheme: other tools care about these files as well. For example, merlin uses `.cmti` so with this scheme if you decide not to document a file then you also lose some merlin support. There may well be other tools (either now or in the future) which rely on cmti files, so I don't think it is a good idea for one of those tools to rely on them not existing.

> Besides it is an established good practice to write mli files to define your APIs.

In most cases but not all. There are valid software engineering reasons to not have mli files for some modules. But really this is beside the point, OCaml always has and always will support modules defined without .mli files so the documentation tooling should be able to handle them. It is not the job of a documentation rule to enforce its own vision of coding standards.

I strongly believe that by default a documentation tool should produce the most accurate documentation it can -- i.e. the most accurate description of the user's typing environment when using a package. If package authors wish to tell white lies to their users they should have to explicitly opt in to that behaviour -- preferably in a way that communicates this directly with the documentation tools without affecting other tools in the ecosystem.

There are a couple additional benefits to having a `@hidden` tag as well:
 - It can be used on submodules and other entities (e.g. values).
 - It continues to work in situations where the documentation is being generated directly from the source tree rather than from the installation tree (as is the case within Jane St.).

**Comment by dbuenzli** [comment]
On Tuesday 3 January 2017 at 10:31, Leo White wrote:
> Good point. Although to me that just shows another problem with the current scheme: other tools care about these files as well. For example, merlin uses .cmti so with this scheme if you decide not to document a file then you also lose some merlin support.

 
That's what you want, because you want to avoid exposing internal names to the end user of the API. It is equivalent to the idea of not installing `cmi` files so that users do not start fiddling with your internal names which is something OCaml packages have been doing for a very long time. Exposing internal names is just plain confusing for the end-user trying to learn an API.

> In most cases but not all. There are valid software engineering reasons to not have mli files for some modules. But really this is beside the point, OCaml always has and always will support modules defined without .mli files so the documentation tooling should be able to handle them. It is not the job of a documentation rule to enforce its own vision of coding standards.
 
Why not ? If people don't like it they should not use it. odig is just enforcing what is done by the vast majority of packages out there. Once opam v2.0 is out I may consider the idea of adding more control to this via an `x-odig-use-cmt:` field where you could list compilation unit names whose `cmt` files should be considered.

> If package authors wish to tell white lies to their users they should have to explicitly opt in to that behaviour -- preferably in a way that communicates this directly with the documentation tools without affecting other tools in the ecosystem.
 
I don't see how hiding internal names means telling white lies to users. If that's what you think then you don't believe in abstraction. It is an unfortunate state of affairs that OCaml's linking model is not able to allow us to hide these name properly at the link level. However it's not because of this that we should present all these internal names at the documentation level since those are not supposed to be used and only increase the information entropy for someone trying to learn and use an API which is something good documentation should try to avoid.

> There are a couple additional benefits to having a @hidden tag as well:
> It can be used on submodules and other entities (e.g. values).
> It continues to work in situations where the documentation is being generated directly from the source tree rather than from the installation tree (as is the case within Jane St.).

 

I'm not against an @hidden tag, but FWIW it doesn't exist yet. Besides we already have stop comments to use on submodules and other entities. Regarding your last point I generally don't want documentation I generate directly from sources to hide things as it means I'm hacking on the project and there I'm interested in seing all the names, internal ones included.

Best, 

Daniel

**Comment by lpw25** [comment]
> That's what you want, because you want to avoid exposing internal names to the end user of the API.
> ...
> I don't see how hiding internal names means telling white lies to users.

These are not proper internal names. We are talking about modules for which the `.cmi` file has been installed. They are being deliberately made available for use by the user. Sometimes people want to be able to remove them from documentation anyway, but this is definitely a little white lie about what their package provides.

Now currently OCaml's linking issues make such things a necessity, but there is no way to tell when this is the case without the users input. Doing this with direct explicit input (e.g. `@hidden`) rather than using a criteria which also frequently occurs in the wild for other reasons (i.e. missing cmti files) and can interfere with other tooling seems obviously superior to me.

> Why not ?

This means that `odig` will not be able to generate proper documentation for quite a few libraries, including almost all of Jane Street's libraries. Obviously I would like to avoid that situation.

> If people don't like it they should not use it.

Except that `odig`'s users are not the package authors. `odig`'s users are the people trying to get documentation for packages they have installed. They don't get to decide whether the libraries they use conform to your personal coding standards.

**Comment by dbuenzli** [comment]
> These are not proper internal names. We are talking about modules for which the .cmi file has been installed.

Well I was not. I was referring to packages `P` that namespace their modules *without* using module aliases in which case their internal `P_*` compilation units may be hidden by not installing the `.cmi` file (though formally they can bite you at link time, which is why you prefix them with the name of your package). 

Aside, I think that this is the way we should be able to structure our modules (which would be perfect if the link problem could be solved and with dead code elimination). Module aliases in my opinion just introduced more naming noise in the system without really solving any problem since you can no longer hide the toplevel names to the end-user, it feels like *feeding the multitude* for names, which is not a good idea.

> Except that odig's users are not the package authors. odig's users are the people trying to get documentation for packages they have installed. They don't get to decide whether the libraries they use conform to your personal coding standards.

There is benefit in standardizing a notion of ocaml package install, whether you like it or not this is what `odig` is doing, see `odig help packaging` for details. It is an open question to see if people will follow these quite reasonable requirements, but for example `topkg` users do so automatically. Now if Jane St. open source libraries in particular do not want to follow this, it is not my problem.

> Perhaps if you give an example where the user should install the .cmi but not the .cmti in the current scheme it would help to move the discussion forward?

That was not my idea; it was either you'd have both `cmi` and `cmti` or not. So would that criterion work (which I would be willing to implement):

1. Package users denote which compilation units should appear in the docs by installing their `cmi` file. 
2. For each of these files odig looks first for `cmti` then if missing for a `cmt` file, then if none of these exist the `cmi` file.

**Comment by lpw25** [comment]
> So would that criterion work

I should have been clearer earlier: that is exactly the criterion I wanted :-)

**Comment by dbuenzli** [comment]
> Personally, I would also like to see modules that only have a .cmi file be included in the documentation by default.

@lpw25 is odoc supposed to grok `cmi` files ? I implemented the above criterion but `odoc compile` bails out with: 

```
odig: [EXEC:8587] ['odoc' 'compile' '-I'
                   '/Users/dbuenzli/.opam/4.03.0/lib/ocaml/' '--pkg' 'result'
                   '-o'
                   '/Users/dbuenzli/.opam/4.03.0/var/cache/odig/cache/result/result.odoc'
                   '/Users/dbuenzli/.opam/4.03.0/lib/result/result.cmi']
odoc: internal error, uncaught exception:
      Failure("Not_a_typedtree")
```

**Comment by trefis** [comment]
odoc is supposed to work on `cmi` files. The fact that it doesn't is a bug that I will look at today.

**Comment by trefis** [comment]
Bug fixed by https://github.com/ocaml-doc/odoc/commit/9ba1af08b2fe4a6fc6206dec6b9ac0bd8497b0e1 .
Also, since https://github.com/ocaml-doc/odoc/commit/4010efa8ab85875db100cf198de250c0bae1dee6 odoc now warns when one is using a `cmt` while the `cmti` should be used.

**Comment by dbuenzli** [comment]
I went for the easiest which means that I do the dep analysis on the `cmi` files of packages, then at the point of generating the `.odoc` I substitute the `cmi` with a `cmti` or `cmt` if there is one at the same location with the same `cmi` hash.

**Comment by lpw25** [comment]
That sounds like the best way to do it.

**Comment by dbuenzli** [comment]
@lpw25 are you sure ? 

It seems cohttp's install is wrong, it's missing the `cmti` file, and `odoc` warns: 

```
> odig odoc cohttp --force 
Processing cohttp.
WARNING: not processing the "interface" file. Using "/Users/dbuenzli/.opam/4.03.0/lib/cohttp/cohttp.cmt" while you should use the .cmti file
```

Now if you look at http://docs.mirage.io/cohttp/Cohttp/index.html the aliases are never resolved and the reason is that I never `odoc` any of compilation units mentioned on the right hand-side. That's because I lookup the deps on `cohttp.cmi` which mention none of these, not even without digest: 

```
> ocamlobjinfo /Users/dbuenzli/.opam/4.03.0/lib/cohttp/cohttp.cmi
File /Users/dbuenzli/.opam/4.03.0/lib/cohttp/cohttp.cmi
Unit name: Cohttp
Interfaces imported:
	ec57b1b12a95a9fe7be61ca72559ce81	Cohttp
	f17596e00890cdbfa772cbc596b3ec17	Uri
	331e41ad213579d006efd84f19005bd5	Unix
	c9608ce7bf745054a217110dcaac126e	Sys
	c28a3ca42a30c6ffa0bbab4a05329226	String
	0b2cb4ad5159673670474028f5fac7a6	Sexplib
	f665d1463ac108184ac6ad6d8bac076e	Random
	0145d8daf24f9afd43ffac3c376fa3c4	Printf
	999b28e3b7638771c87eebf5a8325e42	Pervasives
	ecf089d7539fcff97623be26ecebf193	Nativeint
	ac5f6095cc0a546330ada0df0986a497	List
	330cec55af19abb867bbde7885b2588f	Lexing
	b2e565a5cdbd351dc15bc9061d30c458	Lazy
	8deb8d60f2294e2f3dc6971e7f2efba2	Int64
	d0de3bfd44513ff6fd70cbf476e9fa55	Int32
	049026f8240c3b61bd91f719b0f55877	Hashtbl
	60c2e7663dd57d13b5920931742e1c10	Format
	b0d81fed7b0700228fa79cf4ea564f9e	Fieldslib
	def386d89a071f0355f7bda7e3a074fd	Complex
	4a517d12500bc3789093103f6fee94bf	Char
	9642e3ed163e46770985ca668738ed5f	CamlinternalFormatBasics
	6dc691300ced97c0e319cbcc0a715044	Bytes
	3bd1af04573ce2da7fc3dc04403e852e	Buffer
	7cb259b8efbf4550648d25651a3342ee	Bigarray
```

Yet `cohttp.cmt` has them (but as [mentioned](https://github.com/dbuenzli/odig/issues/2#issuecomment-270363147) I do not perform the dependency analysis on these). 

```
> ocamlobjinfo /Users/dbuenzli/.opam/4.03.0/lib/cohttp/cohttp.cmt
File /Users/dbuenzli/.opam/4.03.0/lib/cohttp/cohttp.cmt
Cmt unit name: Cohttp
Cmt interfaces imported:
	8ef64ebc8f59523dc7e48ab95e8315c6	Accept
	5034b8dc4e4aef2bdcae003d9e868b65	Accept_lexer
	085fb1347e8b7c092535a99c8063408b	Accept_parser
	63dfaca7ff489fa3235245fc40fa3407	Accept_types
	59e57bb57f75822c0d5a352731f0595d	Auth
	7cb259b8efbf4550648d25651a3342ee	Bigarray
	d5d72f60c47e7e4d50fbcefaa0a9a030	Body
	3bd1af04573ce2da7fc3dc04403e852e	Buffer
	6dc691300ced97c0e319cbcc0a715044	Bytes
	9642e3ed163e46770985ca668738ed5f	CamlinternalFormatBasics
	4a517d12500bc3789093103f6fee94bf	Char
	54d520cf6d65a916fa68f49e939dcfde	Code
	ec57b1b12a95a9fe7be61ca72559ce81	Cohttp
	def386d89a071f0355f7bda7e3a074fd	Complex
	54700c5021890d0c9c7812d2d1150e24	Conf
	82c6c8846dde5aff852d91ccc931e7ba	Connection
	19ff8160369e53f21c0eed4d178ec502	Cookie
	b0d81fed7b0700228fa79cf4ea564f9e	Fieldslib
	60c2e7663dd57d13b5920931742e1c10	Format
	049026f8240c3b61bd91f719b0f55877	Hashtbl
	806a24c047bda63656a0e382d434baa9	Header
	a0497745de45ada3f8af3e96d1508364	Header_io
	d0de3bfd44513ff6fd70cbf476e9fa55	Int32
	8deb8d60f2294e2f3dc6971e7f2efba2	Int64
	b2e565a5cdbd351dc15bc9061d30c458	Lazy
	330cec55af19abb867bbde7885b2588f	Lexing
	d02e344d00b27a3f0e1b25389e8953ca	Link
	ac5f6095cc0a546330ada0df0986a497	List
	ecf089d7539fcff97623be26ecebf193	Nativeint
	999b28e3b7638771c87eebf5a8325e42	Pervasives
	0145d8daf24f9afd43ffac3c376fa3c4	Printf
	f665d1463ac108184ac6ad6d8bac076e	Random
	753e2dbc69c1c3d03844677df51ca7f2	Request
	4718e4e61378c43a3bdbdcc4e8afa98a	Response
	57959b9b289d987e370eb7d46e744642	S
	0b2cb4ad5159673670474028f5fac7a6	Sexplib
	c28a3ca42a30c6ffa0bbab4a05329226	String
	03514f8b8869f80076cbb8e8284adf8f	String_io
	c9608ce7bf745054a217110dcaac126e	Sys
	2cd5afe22158d4530416dc691a70107d	Transfer
	a76d027a71d1e0c977135742e3103e10	Transfer_io
	331e41ad213579d006efd84f19005bd5	Unix
	f17596e00890cdbfa772cbc596b3ec17	Uri
Source file: (none)
Compilation flags: ocamlopt.opt -pack -g -annot -bin-annot -I lib -o lib/cohttp.cmx lib/code.cmx lib/accept_types.cmx lib/accept_parser.cmx lib/accept_lexer.cmx lib/accept.cmx lib/auth.cmx lib/conf.cmx lib/link.cmx lib/transfer.cmx lib/header.cmx lib/s.cmi lib/cookie.cmx lib/transfer_io.cmx lib/header_io.cmx lib/request.cmx lib/response.cmx lib/connection.cmx lib/body.cmx lib/string_io.cmx
Load path:  lib /Users/dbuenzli/.opam/4.03.0/lib/ocaml
cmt interface digest: 
```
So: 

1. Is my strategy wrong ? 
2. Or is cohttp's build broken ?

(/cc @avsm)

**Comment by lpw25** [comment]
The strategy is mostly right, but does not work for `-pack`. Firstly it is worth noting that there are two kinds of `-pack`: ones with an explicit `.mli` file and ones without. The ones with `.mli` files should not need any special treatment: the user should just install the corresponding `.cmti` file. For `-pack` without an `.mli` file there are two problems:

1. A pack's `.cmi` file will not include the digests of the modules that went into the pack (after all the whole point is to hide these modules).
2. The modules that went into the pack won't have their `.cmi` files installed (they technically can have them installed -- but normally the aim is to hide these modules from the outside world).

The way `odoc` will support packs is that it expects these inner modules to be compiled with `odoc compile --hidden` so that their information is available to odoc but they won't generate any html (you can run `odoc html` on them if you want but it will just be a no-op).

So the rule above becomes:
1. Package devs denote which compilation units should appear in the docs by installing their cmi file.
2. For each of these files odig looks first for cmti then if missing for a cmt file, then if none of these exist the cmi file.
3. For cmti/cmt files which have no corresponding cmi file odig will call `odoc compile --hidden`

For the dependencies issue, I guess you might have to read the `cmt` file to get accurate dependencies. I can't see any other way to get the information. In general it might be better to do the dependency resolution on the information from the file you intend to read -- but I don't know how well that fits into how odig manages things.

**Comment by dbuenzli** [comment]
Thanks Leo for the detailed explanation. 

> The way odoc will support packs

This is for elsewhere but shouldn't we simply deprecate `-pack` ?  The hack seems to be a constant source of annoyance.

**Comment by lpw25** [comment]
Whilst `-pack` is not the best way to do namespaces it still has its uses -- although mostly for the form with an explicit `.mli` -- so I don't think it will ever be deprecated. It's also likely to be expanded at some point to support creating functors (see the "big functor patch"), which would be very useful but still suffer from the same issues from an odig/odoc perspective.

So given that it is unlikely to be deprecated, and that it is already widely used, I think we should support it. From an odoc perspective the support already exists. For odig the only difficult change is getting dependencies from `.cmt` files, which is probably more technically correct anyway. A `.cmt` file for a module which has an `.mli` file could always have different dependencies from its `.cmi` file. Obviously we don't recommend using such files for generating docs, since the `.cmti` file is more accurate, but if any future tool wants to read `.cmt` files (for example a code browser or debugger) then they are going to want dependencies handled this way anyway.

**Comment by dbuenzli** [comment]
> It's also likely to be expanded at some point to support creating functors (see the "big functor patch"),

People do want to live miserable lifes don't they ?

**Comment by dbuenzli** [comment]
Closing this in favor of #28 which is the actual issue.
