### ISSUE TITLE
development mode for odig that highlights non-odig packages in HTML

### ISSUE THREAD

**Issue by avsm** [dbuenzli/odig#8]
A bunch of us in MirageOS have been porting libraries to use odig so that they show up nicely in the http://docs.mirage.io online browser.  It would be convenient if there were a development lint option that we can pass to `odig ocamldoc` that highlights in the output HTML which packages do not currently install the license, changes and readme, so that we can remedy it.

**Comment by dbuenzli** [comment]
I was rather planning to single-out those that simply don't have an `opam` file installed since that's important for the future.

Note that if you plan to implement `odig` conventions via `topkg` then the following should give you a list of OPAM packages tagged `org:mirage` and that do not depend on `topkg`.

```
{ opam list --depends-on topkg -s; opam list --depends-on topkg -s; opam search -s org:mirage; } | sort | uniq -u
```

**Comment by dbuenzli** [comment]
Since cee4611c737697897fe8f7 the package list indicates the version of the package. If it cannot be determined via the installed `opam` file a `?` will be displayed which you can take as a hint that the package does not implement `odig`'s conventions. Once the latter are better established, an `odig lint` command should be provided.
